spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/${db_name}
spring.datasource.username=${my_db_username}
spring.datasource.password=${my_db_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.public.key=${JWT_PUBLIC_KEY}
jwt.private.key=${JWT_PRIVATE_KEY}